checks:
  method-complexity:
    config:
      threshold: 16
  method-lines:
    config:
      threshold: 35
  argument-count:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 40 # Data classes can have a lot of getter/setters
  return-statements:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 80
  identical-code:
    config:
      threshold: 60
exclude_patterns:
  - "app/src/main/java/ch/epfl/sweng/eventmanager/repository/room/daos"
  - "app/src/main/java/ch/epfl/sweng/eventmanager/repository/impl"
  - "app/src/androidTest/"
  - "app/src/test/"
  - "app/src/main/java/ch/epfl/sweng/eventmanager/ui/event/interaction/fragments/EventMapFragment.java"
  - "app/src/main/java/ch/epfl/sweng/eventmanager/ui/event/interaction/fragments/EventMapEditionFragment.java"
