checks:
  method-complexity:
    config:
      threshold: 16
  method-lines:
    config:
      threshold: 35
  argument-count:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 8
  identical-code:
    config:
      threshold: 6
exclude_patterns:
  - "app/src/main/java/ch/epfl/sweng/eventmanager/repository/room/daos"
  - "app/src/main/java/ch/epfl/sweng/eventmanager/repository/impl"
  - "app/src/androidTest/"
  - "app/src/test/"
