language: android
env:
  - ABI_IMAGE=armeabi-v7a-android ABI=armeabi-v7a API=16 VIEW_AVD_LOGS=1 EMU_OPTS="-noaudio"
  - ABI_IMAGE=armeabi-v7a-android ABI=armeabi-v7a API=18 VIEW_AVD_LOGS=1
  - ABI_IMAGE=armeabi-v7a-android ABI=armeabi-v7a API=19 VIEW_AVD_LOGS=1
  - ABI_IMAGE=armeabi-v7a-android ABI=armeabi-v7a API=24 VIEW_AVD_LOGS=1

  #- ABI_IMAGE=armeabi-v7a-google_apis ABI=google_apis/armeabi API=16
  #- ABI_IMAGE=armeabi-v7a-google_apis ABI=google_apis/armeabi-v7a API=24

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    # The SDK version used by the system image
    - android-$API
    # The system image, to run an emulator during the tests
    - sys-img-$ABI_IMAGE-$API
    - tools
    - platform-tools
before_script:
  # Ensure images are up to date
  #} - echo "y" | android update sdk -a --no-ui --filter android-$API
  # - echo "y" | android update sdk -a --no-ui --filter sys-img-$ABI_IMAGE-$API
  # Emulator Management: Create, Start and Wait
  - android list target
  - echo no | android create avd --force -n test -t android-$API --abi $ABI
  - emulator -avd test -no-window -verbose -memory 1536 $EMU_OPTS & # no-audio causes failures, so I removed it
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  # Disable transitions
  - adb shell settings put global window_animation_scale 0.0
  - adb shell settings put global transition_animation_scale 0.0
  - adb shell settings put global animator_duration_scale 0.0
  # Set twitter key
  - sed -i 's/${CONSUMER_SECRET}/$TWITTER_CONSUMMER_SECRET/' app/src/main/res/values/twitter.xml
  - adb shell input keyevent 4 &
  # Set up Code Climate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # Take a screenshot
  - targetName=$(date +%s | sha256sum | base64 | head -c 8)
  - adb shell screencap -p | sed 's/\r$//' > $targetName-before.png
  - echo $targetName
  - scp -oStrictHostKeyChecking=no -i id_rsa $targetName-before.png zyuiop@atlas.zyuiop.net:~/screenshots/
script:
  - if [ -n "$VIEW_AVD_LOGS" ] ; then adb logcat *:I & LOGCAT_PID=$!; fi
  - ./gradlew build connectedCheck jacocoTestReport
  - if [ -n "$LOGCAT_PID" ] ; then kill $LOGCAT_PID; fi
  # Take a screenshot
  - adb shell screencap -p | sed 's/\r$//' > $targetName-after.png
  - scp -oStrictHostKeyChecking=no -i id_rsa $targetName-after.png zyuiop@atlas.zyuiop.net:~/screenshots/
after_script:
  # Report test coverage to Code Climate
  - export JACOCO_SOURCE_PATH=app/src/main/java/
  - ./cc-test-reporter format-coverage ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
before_install:
- openssl aes-256-cbc -K $encrypted_d1100674ed4a_key -iv $encrypted_d1100674ed4a_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
